rm psi/cutestuff/network/httppoll.cpp
rm psi/iris/jabber/filetransfer.cpp
rm psi/iris/xmpp-core/connector.cpp
rm psi/iris/xmpp-core/protocol.cpp
rm psi/iris/xmpp-core/stream.cpp
rm psi/iris/xmpp-im/xmpp_task.cpp
rm psi/iris/xmpp-im/xmpp_tasks.cpp
rm psi/src/privacy/privacylist.cpp
rm psi/src/privacy/psiprivacymanager.cpp
rm psi/src/options/opt_appearance.cpp
rm psi/src/options/opt_application.cpp
rm psi/src/options/opt_events.cpp
rm psi/src/options/opt_iconset.cpp
rm psi/src/options/optionsdlg.cpp
rm psi/src/options/opt_sound.cpp
rm psi/src/options/opt_status.cpp
rm psi/src/psigrowlnotifier.cpp
rm psi/src/aboutdlg.cpp
rm psi/src/accountmodifydlg.cpp
rm psi/src/applicationinfo.cpp
rm psi/src/chatdlg.cpp
rm psi/src/common.cpp
rm psi/src/contactview.cpp
rm psi/src/psicon.cpp
rm psi/src/infodlg.cpp
rm psi/src/filetransdlg.cpp
rm psi/src/mainwin.cpp
rm psi/src/main.cpp
rm psi/src/mainwin_p.cpp
rm psi/src/psichatdlg.cpp
rm psi/src/mucconfigdlg.cpp
rm psi/src/mucjoindlg.cpp
rm psi/src/psiaccount.cpp
rm psi/src/psiactionlist.cpp
rm psi/src/psipopup.cpp
rm psi/src/psi_profiles.cpp
rm psi/src/statusdlg.cpp
rm psi/src/psioptions.cpp
