del psi\cutestuff\network\httppoll.cpp
del psi\iris\jabber\filetransfer.cpp
del psi\iris\xmpp-core\connector.cpp
del psi\iris\xmpp-core\protocol.cpp
del psi\iris\xmpp-core\stream.cpp
del psi\iris\xmpp-im\xmpp_task.cpp
del psi\iris\xmpp-im\xmpp_tasks.cpp
del psi\src\privacy\privacylist.cpp
del psi\src\privacy\psiprivacymanager.cpp
del psi\src\options\opt_appearance.cpp
del psi\src\options\opt_application.cpp
del psi\src\options\opt_events.cpp
del psi\src\options\opt_iconset.cpp
del psi\src\options\optionsdlg.cpp
del psi\src\options\opt_sound.cpp
del psi\src\options\opt_status.cpp
del psi\src\psigrowlnotifier.cpp
del psi\src\aboutdlg.cpp
del psi\src\accountmodifydlg.cpp
del psi\src\applicationinfo.cpp
del psi\src\chatdlg.cpp
del psi\src\common.cpp
del psi\src\contactview.cpp
del psi\src\psicon.cpp
del psi\src\infodlg.cpp
del psi\src\filetransdlg.cpp
del psi\src\mainwin.cpp
del psi\src\main.cpp
del psi\src\mainwin_p.cpp
del psi\src\psichatdlg.cpp
del psi\src\mucconfigdlg.cpp
del psi\src\mucjoindlg.cpp
del psi\src\psiaccount.cpp
del psi\src\psiactionlist.cpp
del psi\src\psipopup.cpp
del psi\src\psi_profiles.cpp
del psi\src\statusdlg.cpp
del psi\src\psioptions.cpp
del psi\src\groupchatdlg.cpp
del psi\src\serverinfomanager.cpp
