######################################################################
# Automatically generated by qmake (2.00a) Sun Jun 18 16:55:37 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .
QT += svg xml

# Input
HEADERS += mainwindow.h svgstreamrenderer.h svgstreamwidget.h
SOURCES += main.cpp mainwindow.cpp svgstreamrenderer.cpp svgstreamwidget.cpp
