#!/bin/sh

CS_BASE=../../../cutestuff
QCA_BASE=../../../qca
IRIS_BASE=../..

# import cutestuff
mkdir cutestuff
cp -a $CS_BASE/util cutestuff
cp -a $CS_BASE/network cutestuff

# import qca
mkdir qca
cp -a $QCA_BASE/src/* qca

# import iris
mkdir iris
cp -a $IRIS_BASE/libidn iris
cp -a $IRIS_BASE/libidn.pri iris
cp -a $IRIS_BASE/include iris
cp -a $IRIS_BASE/xmpp-core iris
cp -a $IRIS_BASE/xmpp-im iris
cp -a $IRIS_BASE/jabber iris
cp -a $IRIS_BASE/iris.pri iris

# other stuff
cp -a $IRIS_BASE/cs.pri .
cp -a $IRIS_BASE/example/example.pri .
cp -a $IRIS_BASE/COPYING .

