set(VER_FILE ${PROJECT_SOURCE_DIR}/version)
set(DEFAULT_VER "1.3")
if(EXISTS "${VER_FILE}")
    message(STATUS "Found Psi version file: ${VER_FILE}")
    file(STRINGS "${VER_FILE}" VER_LINES)
    if(IS_PSIPLUS)
        string(REGEX MATCHALL "^([0-9]+\\.[0-9]+\\.[0-9]+)+.+Psi:([a-fA-F0-9]+)+.+Psi\\+:([a-fA-F0-9]+)+" VER_LINE_A ${VER_LINES})
        if(${CMAKE_MATCH_COUNT} EQUAL 3)
            if(CMAKE_MATCH_1)
                set(APP_VERSION ${CMAKE_MATCH_1})
            endif()
            if(CMAKE_MATCH_2)
                set(PSI_REVISION ${CMAKE_MATCH_2})
            endif()
            if(CMAKE_MATCH_3)
                set(PSI_PLUS_REVISION ${CMAKE_MATCH_3})
            endif()
        endif()
        if(APP_VERSION)
            message(STATUS "Psi version found: ${APP_VERSION}")
        elseif(NOT APP_VERSION AND (NOT PSI_VERSION) )
            message(WARNING "Psi+ version not found! ${DEFAULT_VER} version will be set")
            set(APP_VERSION ${DEFAULT_VER})
        endif()
        if(PSI_REVISION)
            message(STATUS "Psi revision found: ${PSI_REVISION}")
        endif()
        if(PSI_PLUS_REVISION)
            message(STATUS "Psi+ revision found: ${PSI_PLUS_REVISION}")
        endif()
    else()
        string(REGEX MATCH "^[0-9]+\\.[0-9]+" VER_LINE ${VER_LINES})
        if (VER_LINE)
            set(APP_VERSION ${VER_LINE})
            message(STATUS "Psi version found: ${VER_LINE}")
        elseif( NOT PSI_VERSION )
            message(WARNING "Psi version not found! ${DEFAULT_VER} version will be set")
            set(APP_VERSION ${DEFAULT_VER})
        endif()
    endif()
endif()

if( IS_PSIPLUS AND ( APP_VERSION AND ( PSI_REVISION AND PSI_PLUS_REVISION ) ) )
    set(PSIPLUS_VERSION_OBTAINED ON)
elseif( NOT IS_PSIPLUS AND APP_VERSION )
    set(PSI_VERSION_OBTAINED ON)
endif()
